// See https://aka.ms/new-console-template for more information

/* PARAŠYTIPROGRAMĄ, KURI PAPRAŠO VARTOTOJO ĮVESTI GRUPĖS NARIŲ KIEKĮ.
 * JEI NARIŲ KIEKIS LYGUS 1 PROGRAMA IŠVEDA „TAI SOLOATLIKĖJAS“, 
 * JEI NARIŲ KIEKIS 2 -„TAI DUETAS“, 
 * JEI NARIŲ KIEKIS DAUGIAU NEI 2 BET MAŽIAU NEI 10 –„TAI ANSAMBLIS“,
 * JEI DAUGIAU NEI 10 –„TAI KAMERINIS ANSAMBLIS“.JEI VARTOTOJAS PADARO ĮVEDIMO KLAIDĄ –PRANEŠTI IR UŽBAIGTI DARBĄ */

Console.WriteLine("Hello, World!");
